source 'https://github.com/CocoaPods/Specs.git'             #官网仓库地址
source 'https://github.com/caterpillarFly/ZSRepo'           #自己的仓库

target 'ZSThirdKit' do

  pod 'HTestVC'
  
  pod 'ZSQQSDK', '~> 0.0.1'
  pod 'WechatOpenSDK'
  pod 'WeiboSDK'

  target 'ZSThirdKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZSThirdKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
